import os
import re
import glob
import hashlib
import datetime
import subprocess

NB_TYPES = {
    "EXPERIMENT": ["aim", "plan"],
    "RESULT": ["ran", "observed"],
    "FINDING": ["claim", "based on"],
    "DECISION": ["decision", "alternatives", "rationale", "decided by"],
    "ISSUE": ["problem", "impact", "next"],
    "NOTE": ["text"],
    "CORRECTION": ["corrects", "was", "correct"],
}
NB_GENESIS = "0000000000000000000000000000000000000000000000000000000000000000"
NB_HEADER_RE = r"^## (NB-\d{8}-\d{2,}) · (\S+) · ([A-Z]+)(?: · (\S+))?\s*$"
NB_HASH_RE = r"^<!-- sha256=([0-9a-f]{64}) prev=([0-9a-f]{64}) -->\s*$"

def nb_dir(root):
    """Return <root>/notebook."""
    return os.path.join(root, "notebook")

def nb_init(root, project, timezone=None):
    """Create notebook/README.md (conventions + timezone). Never overwrites."""
    d = nb_dir(root)
    os.makedirs(d, exist_ok=True)
    readme = os.path.join(d, "README.md")
    if os.path.exists(readme):
        return {"created": False, "path": readme}
    tz = timezone or (datetime.datetime.now().astimezone().tzname() or "local")
    with open(readme, "w") as fh:
        fh.write(f"# Lab notebook: {project}\n\n- timezone: {tz}\n- started: {nb_now(root, tz).isoformat(timespec='seconds')}\n\n"
                 "Append-only. One page per day (YYYY-MM-DD.md). Entries are never edited or deleted; mistakes are fixed\n"
                 "with a CORRECTION entry. Each entry ends with a SHA-256 hash chained to the previous entry\n"
                 "(verify with nb_check). INDEX.md is generated by nb_index().\n")
    return {"created": True, "path": readme}

def nb_tz(root):
    """Timezone name recorded in notebook/README.md, or None for system local."""
    readme = os.path.join(nb_dir(root), "README.md")
    if os.path.exists(readme):
        m = re.search(r"^- timezone:\s*(\S+)", open(readme).read(), re.M)
        if m and "/" in m.group(1):
            return m.group(1)
    return None

def nb_now(root, tz=None):
    """Current time as an aware datetime in the notebook's timezone."""
    tz = tz if (tz and "/" in tz) else nb_tz(root)
    if tz:
        import zoneinfo
        return datetime.datetime.now(zoneinfo.ZoneInfo(tz))
    return datetime.datetime.now().astimezone()

def nb_entries(root):
    """Parse all daily pages in order -> list of {id, ts, type, exp, title, fields, body, sha, prev, page}."""
    out = []
    for page in sorted(glob.glob(os.path.join(nb_dir(root), "????-??-??.md"))):
        lines = open(page).read().split("\n")
        cur = None
        for line in lines:
            h = re.match(NB_HEADER_RE, line)
            if h:
                cur = {"id": h.group(1), "ts": h.group(2), "type": h.group(3), "exp": h.group(4),
                       "title": "", "fields": {}, "lines": [line], "sha": None, "prev": None,
                       "page": os.path.basename(page)}
                out.append(cur)
                continue
            if cur is None or cur["sha"]:
                continue
            g = re.match(NB_HASH_RE, line)
            if g:
                cur["sha"], cur["prev"] = g.group(1), g.group(2)
                continue
            cur["lines"].append(line)
            t = re.match(r"^\*\*(.+)\*\*\s*$", line)
            if t and not cur["title"]:
                cur["title"] = t.group(1)
            f = re.match(r"^- ([a-z ]+):\s*(.*)$", line)
            if f:
                cur["fields"][f.group(1).strip()] = f.group(2).strip()
    for e in out:
        e["body"] = "\n".join(e.pop("lines")).strip()
    return out

def nb_hash(prev, body):
    """Chain hash of an entry body given the previous entry's hash."""
    return hashlib.sha256((prev + "\n" + body).encode("utf-8")).hexdigest()

def nb_git(root, *args):
    """Run git in root; return CompletedProcess."""
    return subprocess.run(["git", "-C", root] + list(args), capture_output=True, text=True)

def nb_entry(root, type, title, fields, experiment=None, author="agent", links=None, refs=None, commit=True):
    """Append one timestamped, hash-chained entry to today's page; rebuild INDEX.md; git-commit. Returns {id, page, ...}."""
    import fcntl
    type = type.upper()
    if type not in NB_TYPES:
        raise ValueError(f"type must be one of {sorted(NB_TYPES)}")
    missing = [k for k in NB_TYPES[type] if not str(fields.get(k, "")).strip()]
    if missing:
        raise ValueError(f"{type} entry needs fields: {missing}")
    if type == "CORRECTION" and not re.match(r"^NB-\d{8}-\d{2,}$", str(fields["corrects"]).strip()):
        raise ValueError("CORRECTION 'corrects' must be an entry ID like NB-20261002-01")
    d = nb_dir(root)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, ".lock"), "w") as lk:
        fcntl.flock(lk, fcntl.LOCK_EX)
        entries = nb_entries(root)
        known = {e["id"] for e in entries}
        bad = [r for r in (refs or []) + ([fields["corrects"]] if type == "CORRECTION" else []) if r not in known]
        if bad:
            raise ValueError(f"unknown entry IDs referenced: {bad}")
        now = nb_now(root)
        day = now.strftime("%Y%m%d")
        n = 1 + max([int(e["id"].split("-")[2]) for e in entries if e["id"].split("-")[1] == day] or [0])
        eid = f"NB-{day}-{n:02d}"
        head = f"## {eid} · {now.isoformat(timespec='seconds')} · {type}" + (f" · {experiment}" if experiment else "")
        body = [head, f"**{title}**", f"- author: {author}"]
        for k in NB_TYPES[type] + [k for k in fields if k not in NB_TYPES[type]]:
            v = fields[k]
            if isinstance(v, (list, tuple)):
                body.append(f"- {k}:")
                body += [f"  - {x}" for x in v]
            else:
                body.append(f"- {k}: {v}")
        rev = nb_git(root, "rev-parse", "--short", "HEAD")
        lk_links = list(links or [])
        if rev.returncode == 0:
            lk_links.insert(0, f"repo@{rev.stdout.strip()}")
        if lk_links:
            body.append("- links: " + "; ".join(lk_links))
        if refs:
            body.append("- refs: " + ", ".join(refs))
        body = "\n".join(body)
        prev = entries[-1]["sha"] if entries else NB_GENESIS
        sha = nb_hash(prev, body)
        page = os.path.join(d, now.strftime("%Y-%m-%d") + ".md")
        new_page = not os.path.exists(page)
        with open(page, "a") as fh:
            if new_page:
                fh.write(f"# Lab notebook: {now.strftime('%Y-%m-%d')}\n")
            fh.write("\n" + body + f"\n<!-- sha256={sha} prev={prev} -->\n")
        nb_index(root)
    out = {"id": eid, "page": os.path.relpath(page, root), "sha": sha[:12], "committed": False}
    if commit and nb_git(root, "rev-parse", "--is-inside-work-tree").returncode == 0:
        files = [os.path.relpath(page, root), os.path.join("notebook", "INDEX.md")]
        if os.path.exists(os.path.join(d, "README.md")):
            files.append(os.path.join("notebook", "README.md"))
        nb_git(root, "add", "--", *files)
        r = nb_git(root, "commit", "-q", "-m", f"notebook: {eid} {type} {title}"[:120], "--", *files)
        out["committed"] = r.returncode == 0
        if r.returncode:
            out["note"] = (r.stdout + r.stderr).strip()[:300]
    return out

def nb_index(root):
    """Rebuild notebook/INDEX.md: entries by experiment, decisions, open issues, corrections."""
    es = nb_entries(root)
    corrected = {e["fields"].get("corrects"): e["id"] for e in es if e["type"] == "CORRECTION"}
    cited = set()
    for e in es:
        cited.update(re.findall(r"NB-\d{8}-\d{2,}", e["fields"].get("refs", "")))
    def row(e):
        c = f" — corrected by {corrected[e['id']]}" if e["id"] in corrected else ""
        return f"- [{e['id']}]({e['page']}) · {e['ts'][:16]} · {e['type']} · {e['title']}{c}"
    lines = ["# Notebook index", "<!-- generated by nb_index(); do not edit by hand -->", "",
             f"{len(es)} entries; last: {es[-1]['ts'] if es else '—'}", ""]
    exps = sorted({e["exp"] for e in es if e["exp"]})
    for x in exps:
        lines += [f"## {x}"] + [row(e) for e in es if e["exp"] == x] + [""]
    gen = [e for e in es if not e["exp"]]
    if gen:
        lines += ["## Project-wide"] + [row(e) for e in gen] + [""]
    dec = [e for e in es if e["type"] == "DECISION"]
    lines += ["## Decisions"] + ([f"- [{e['id']}]({e['page']}) {e['fields'].get('decision', '')} (by {e['fields'].get('decided by', '?')})" + (f" — corrected by {corrected[e['id']]}" if e["id"] in corrected else "") for e in dec] or ["- none"]) + [""]
    iss = [e for e in es if e["type"] == "ISSUE" and e["id"] not in cited and e["id"] not in corrected]
    lines += ["## Open issues (not referenced by any later entry)"] + ([row(e) for e in iss] or ["- none"]) + [""]
    path = os.path.join(nb_dir(root), "INDEX.md")
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    return {"entries": len(es), "experiments": exps, "decisions": len(dec), "open_issues": len(iss)}

def nb_check(root):
    """Verify the hash chain, ID order, timestamps, required fields, and that refs/corrects point to existing entries."""
    es = nb_entries(root)
    ids = [e["id"] for e in es]
    issues = []
    prev = NB_GENESIS
    seen = set()
    last_ts = None
    for e in es:
        if e["sha"] is None:
            issues.append(f"{e['id']}: missing hash line")
        else:
            if e["prev"] != prev:
                issues.append(f"{e['id']}: chain break (prev hash does not match preceding entry — entry deleted or reordered?)")
            if nb_hash(e["prev"], e["body"]) != e["sha"]:
                issues.append(f"{e['id']}: content changed after it was written")
            prev = e["sha"]
        if e["id"] in seen:
            issues.append(f"{e['id']}: duplicate ID")
        seen.add(e["id"])
        try:
            ts = datetime.datetime.fromisoformat(e["ts"])
            if last_ts and ts < last_ts:
                issues.append(f"{e['id']}: timestamp earlier than previous entry")
            last_ts = ts
        except ValueError:
            issues.append(f"{e['id']}: bad timestamp {e['ts']}")
        if e["type"] not in NB_TYPES:
            issues.append(f"{e['id']}: unknown type {e['type']}")
        else:
            miss = [k for k in NB_TYPES[e["type"]] if k not in e["fields"]]
            if miss:
                issues.append(f"{e['id']}: missing fields {miss}")
        for r in re.findall(r"NB-\d{8}-\d{2,}", e["fields"].get("refs", "") + " " + e["fields"].get("corrects", "")):
            if r not in ids[:ids.index(e["id"])]:
                issues.append(f"{e['id']}: references {r}, which is not an earlier entry")
    return {"entries": len(es), "ok": not issues, "issues": issues, "head": prev[:12]}

def nb_export_decisions(root, path="audit/DECISIONS.md"):
    """Write DECISION entries (with corrections noted) to a DECISIONS.md for the reproducible audit bundle."""
    es = nb_entries(root)
    corrected = {e["fields"].get("corrects"): e["id"] for e in es if e["type"] == "CORRECTION"}
    lines = ["# Decisions", "<!-- generated from notebook/ by nb_export_decisions(); do not edit by hand -->", ""]
    for e in (e for e in es if e["type"] == "DECISION"):
        f = e["fields"]
        lines += [f"## {e['id']} · {e['ts']}" + (f" · {e['exp']}" if e["exp"] else ""), f"**{e['title']}**",
                  f"- decision: {f.get('decision')}", f"- alternatives: {f.get('alternatives')}",
                  f"- rationale: {f.get('rationale')}", f"- decided by: {f.get('decided by')}"]
        if e["id"] in corrected:
            lines.append(f"- superseded/corrected by: {corrected[e['id']]}")
        lines.append("")
    full = os.path.join(root, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as fh:
        fh.write("\n".join(lines))
    return {"path": path, "decisions": sum(1 for e in es if e["type"] == "DECISION")}
