import os
import re
import datetime
import subprocess
import urllib.request
import urllib.parse

REFS_HEADING = "## References"
SUPP_HEADING = "## Supplementary material"
REFS_NOTE = "<!-- generated by outline_render_refs() from main-text citations; do not edit by hand -->"

OUTLINE_TEMPLATE = """# {title}

- target venue: {venue}
- thesis: {thesis}
- last updated: {date}

## Abstract
- problem: <one line>
- approach: <one line>
- main result: <one line, filled when known>
- implication: <one line>

## 1 Introduction
- <background claim, one per line> (@?key2024)
- gap: <what prior work does not do> (@?key2024)

### RQ1 — <question>
- hypothesis: <expected answer>
- status: open

## 2 Methods

### M1 — <method>
- used in: E01
- params: <key settings>
- rationale: <one claim> (@?key2024)
- details: [S-M1]

## 3 Results

### E01 — <short name>
- addresses: RQ1
- status: planned
- design: <one line>
- data: <dataset name> [S-D1]
- methods: M1
- result: <experiments/01_name/ or artifact:VERSION_ID>
- finding: <one line, filled when done>
- details: [S-E01]

## 4 Discussion
- <interpretation / limitation / threat to validity / open issue>

## References
<!-- generated by outline_render_refs() from main-text citations; do not edit by hand -->

## Supplementary material

### S-M1 — <method: derivation / math>
- <definitions, objective, update equations in LaTeX, e.g. $\\mathcal{{L}} = \\ldots$>
- <assumptions, complexity, implementation notes>

### S-D1 — <dataset name>
- source: <accession / URL / version / access date>
- size: <n samples, features, classes>
- preprocessing: <filters, normalization, splits>
- caveats: <batch effects, licensing, known issues>

### S-E01 — <experiment>
- settings: <hyperparameters, seeds, hardware, runtime>
- metrics: <exact definitions>
"""

CHANGELOG_TEMPLATE = "# Outline changelog: {title}\n\nNewest first. Each entry: what changed in outline.md and why.\n\n- {date} — outline created\n"
BIB_HEADER = "% refs.bib — every entry carries verified = {YYYY-MM-DD via doi|pmid|arxiv|url}\n"
EVIDENCE_HEADER = "# Evidence log\n\nOne line per cite key: `- @key — what it shows — checked: <DOI/PMID + section/page/figure>`\n\n"

def outline_paths(root):
    """Return dict of the outline files under <root>/paper/."""
    p = os.path.join(root, "paper")
    return {"outline": os.path.join(p, "outline.md"),
            "changelog": os.path.join(p, "CHANGELOG.md"),
            "bib": os.path.join(p, "refs.bib"),
            "evidence": os.path.join(p, "evidence.md")}

def outline_init(root, title, venue="TBD", thesis="TBD"):
    """Create paper/outline.md, CHANGELOG.md, refs.bib, evidence.md from templates. Never overwrites."""
    paths = outline_paths(root)
    os.makedirs(os.path.dirname(paths["outline"]), exist_ok=True)
    today = datetime.date.today().isoformat()
    contents = {"outline": OUTLINE_TEMPLATE.format(title=title, venue=venue, thesis=thesis, date=today),
                "changelog": CHANGELOG_TEMPLATE.format(title=title, date=today),
                "bib": BIB_HEADER, "evidence": EVIDENCE_HEADER}
    made = []
    for k, path in paths.items():
        if os.path.exists(path):
            continue
        with open(path, "w") as fh:
            fh.write(contents[k])
        made.append(path)
    return {"created": made, "existing": [p for p in paths.values() if p not in made]}

def outline_split(text):
    """Split outline text into (main, references, supplement) by the two fixed headings."""
    main, rest = (text.split("\n" + REFS_HEADING, 1) + [""])[:2]
    if SUPP_HEADING in main:
        main, supp = main.split("\n" + SUPP_HEADING, 1)
        return main, "", supp
    refs, supp = (rest.split("\n" + SUPP_HEADING, 1) + [""])[:2]
    return main, refs, supp

def outline_cites(text):
    """Return (verified_keys, unverified_keys) from (@key; @?key) groups in text."""
    cites, unverified = set(), set()
    for grp in re.findall(r"\(([^()]*@[^()]*)\)", text):
        for q, key in re.findall(r"@(\??)([A-Za-z][\w:.\-]*\w)", grp):
            (unverified if q else cites).add(key)
    return cites, unverified - cites

def outline_blocks(text, prefixes):
    """Parse '### <ID> — title' blocks and their '- key: value' fields for ID prefixes like ('RQ','E','M')."""
    pat = re.compile(r"^###\s+(" + "|".join(prefixes) + r")(\d+[a-z]?)\s*[—-]\s*(.*)$")
    out, cur = {}, None
    for line in text.splitlines():
        h = pat.match(line)
        if h:
            cur = h.group(1) + h.group(2)
            out[cur] = {"kind": h.group(1), "title": h.group(3).strip(), "fields": {}}
            continue
        if line.startswith("## ") or line.startswith("### "):
            cur = None
            continue
        f = re.match(r"^-\s+([a-z ]+):\s*(.*)$", line)
        if cur and f:
            out[cur]["fields"][f.group(1).strip()] = f.group(2).strip()
    return out

def outline_parse(root):
    """Parse outline.md: rq/exp/meth blocks (main text), supp blocks, cites per part, [S-ID] pointers."""
    main, refs, supp = outline_split(open(outline_paths(root)["outline"]).read())
    b = outline_blocks(main, ("RQ", "E", "M"))
    mc, mu = outline_cites(main)
    sc, su = outline_cites(supp)
    return {"rq": {k: v for k, v in b.items() if v["kind"] == "RQ"},
            "exp": {k: v for k, v in b.items() if v["kind"] == "E"},
            "meth": {k: v for k, v in b.items() if v["kind"] == "M"},
            "supp": outline_blocks(supp, ("S-M", "S-D", "S-E", "S-[A-Z]")),
            "main_cites": mc, "main_unverified": mu, "supp_cites": sc, "supp_unverified": su,
            "s_links": set(re.findall(r"\[(S-[A-Z]+\d+[a-z]?)\]", main)),
            "has_refs": ("\n" + REFS_HEADING) in open(outline_paths(root)["outline"]).read(),
            "has_supp": bool(supp)}

def outline_bib_entries(root):
    """Return {key: {'verified': bool, 'doi', 'fields'}} parsed from paper/refs.bib."""
    path = outline_paths(root)["bib"]
    if not os.path.exists(path):
        return {}
    text = open(path).read()
    starts = [(m.start(), m.group(1)) for m in re.finditer(r"@\w+\s*\{\s*([^,\s]+)\s*,", text)]
    out = {}
    for i, (pos, key) in enumerate(starts):
        body = text[pos: starts[i + 1][0] if i + 1 < len(starts) else len(text)]
        fields = {k.lower(): v.strip() for k, v in re.findall(r"\b(\w+)\s*=\s*[{\"]((?:[^{}]|\{[^{}]*\})*)[}\"]", body)}
        out[key] = {"verified": "verified" in fields, "doi": fields.get("doi"), "fields": fields}
    return out

def outline_refs(field):
    """Split 'RQ1, RQ2' / 'E01; E02' into IDs."""
    return [t for t in re.split(r"[,;\s]+", field or "") if re.match(r"^(RQ|E|M)\d+[a-z]?$", t)]

def outline_check(root):
    """Consistency report: paper structure, RQ<->E<->M links, [S-ID] pointers, citations vs bib/evidence."""
    o = outline_parse(root)
    bib = outline_bib_entries(root)
    ev_path = outline_paths(root)["evidence"]
    ev_keys = set(re.findall(r"^-\s+@([A-Za-z][\w:.\-]*\w)", open(ev_path).read(), re.M)) if os.path.exists(ev_path) else set()
    issues = []
    if not o["has_refs"]:
        issues.append(f"missing '{REFS_HEADING}' section after the main text")
    if not o["has_supp"]:
        issues.append(f"missing '{SUPP_HEADING}' section after References")
    rq_used, m_used = set(), set()
    for eid, e in o["exp"].items():
        f = e["fields"]
        st = f.get("status", "").split()[0].lower() if f.get("status") else ""
        rqs, ms = outline_refs(f.get("addresses")), outline_refs(f.get("methods"))
        if st != "dropped":
            rq_used.update(rqs)
            m_used.update(ms)
        if not rqs:
            issues.append(f"{eid}: addresses no RQ")
        issues += [f"{eid}: addresses undefined {r}" for r in rqs if r not in o["rq"]]
        issues += [f"{eid}: uses undefined {m}" for m in ms if m not in o["meth"]]
        if st not in ("planned", "running", "done", "dropped"):
            issues.append(f"{eid}: status '{f.get('status')}' not in planned|running|done|dropped")
        res = f.get("result", "")
        if st == "done" and (not res or res.startswith("<")):
            issues.append(f"{eid}: done but no result link")
        if res and not res.startswith(("<", "artifact:")) and not os.path.exists(os.path.join(root, res.split()[0])):
            issues.append(f"{eid}: result path not found: {res.split()[0]}")
    issues += [f"{r}: no active experiment addresses it" for r in o["rq"] if r not in rq_used]
    issues += [f"{m}: not used by any active experiment" for m in o["meth"] if m not in m_used]
    issues += [f"[{s}] pointed to from main text but no supplement block" for s in sorted(o["s_links"] - set(o["supp"]))]
    issues += [f"{s}: supplement block not pointed to from main text" for s in sorted(set(o["supp"]) - o["s_links"])]
    main_all = o["main_cites"] | o["main_unverified"]
    supp_only = sorted((o["supp_cites"] | o["supp_unverified"]) - main_all)
    issues += [f"@{k}: cited in supplement but not in main text" for k in supp_only]
    cites = o["main_cites"]
    report = {
        "n_rq": len(o["rq"]), "n_exp": len(o["exp"]), "n_meth": len(o["meth"]), "n_supp_blocks": len(o["supp"]),
        "n_cited": len(cites),
        "missing_from_bib": sorted(cites - set(bib)),
        "bib_unverified": sorted(k for k in cites & set(bib) if not bib[k]["verified"]),
        "bib_uncited": sorted(set(bib) - cites),
        "missing_from_evidence": sorted(cites - ev_keys),
        "unverified_leads": sorted(o["main_unverified"]),
        "structure": issues,
    }
    report["clean"] = not any(report[k] for k in ("missing_from_bib", "bib_unverified", "missing_from_evidence", "structure"))
    return report

def outline_format_ref(key, entry):
    """One reference line: '- [key] Surname et al. (year). Title. Venue. doi:...'."""
    f = entry.get("fields", {}) if entry else {}
    authors = [a.strip() for a in re.split(r"\s+and\s+", f.get("author", "")) if a.strip()]
    def surname(a):
        return a.split(",")[0].strip() if "," in a else a.split()[-1]
    if not authors:
        who = "?"
    elif len(authors) == 1:
        who = surname(authors[0])
    elif len(authors) == 2:
        who = surname(authors[0]) + " & " + surname(authors[1])
    else:
        who = surname(authors[0]) + " et al."
    title = re.sub(r"[{}]", "", f.get("title", "?"))
    venue = re.sub(r"[{}]", "", f.get("journal") or f.get("booktitle") or f.get("publisher") or "")
    line = f"- [{key}] {who} ({f.get('year', 'n.d.')}). {title}."
    if venue:
        line += f" {venue}."
    if f.get("doi"):
        line += f" doi:{f['doi']}"
    return line

def outline_render_refs(root):
    """Regenerate the References section (between main text and supplement) from main-text citations."""
    path = outline_paths(root)["outline"]
    main, _, supp = outline_split(open(path).read())
    bib = outline_bib_entries(root)
    cites, unverified = outline_cites(main)
    lines = [REFS_HEADING, REFS_NOTE]
    for k in sorted(cites, key=lambda k: outline_format_ref(k, bib.get(k)).lower()):
        lines.append(outline_format_ref(k, bib[k]) if k in bib else f"- [{k}] MISSING FROM refs.bib")
    if unverified:
        lines += ["", "### Unverified leads", "<!-- (@?key): not yet checked against a primary source; never cite in the manuscript -->"]
        lines += [f"- [{k}]" for k in sorted(unverified)]
    text = main.rstrip() + "\n\n" + "\n".join(lines) + "\n\n" + SUPP_HEADING + "\n\n" + supp.strip("\n") + "\n"
    with open(path, "w") as fh:
        fh.write(text.rstrip() + "\n")
    return {"cited": len(cites), "unverified": len(unverified)}

def outline_log(root, message, commit=True):
    """Prepend a dated entry to paper/CHANGELOG.md, bump 'last updated' in outline.md, git-commit paper/ files."""
    paths = outline_paths(root)
    today = datetime.date.today().isoformat()
    o = open(paths["outline"]).read()
    with open(paths["outline"], "w") as fh:
        fh.write(re.sub(r"^- last updated:.*$", f"- last updated: {today}", o, count=1, flags=re.M))
    cl = open(paths["changelog"]).read() if os.path.exists(paths["changelog"]) else "# Outline changelog\n\n"
    m = re.search(r"^- \d{4}-\d{2}-\d{2} — ", cl, re.M)
    entry = f"- {today} — {message}\n"
    cl = cl[:m.start()] + entry + cl[m.start():] if m else cl.rstrip() + "\n\n" + entry
    with open(paths["changelog"], "w") as fh:
        fh.write(cl)
    out = {"logged": entry.strip(), "committed": False}
    if not commit:
        return out
    if subprocess.run(["git", "-C", root, "rev-parse", "--is-inside-work-tree"], capture_output=True).returncode != 0:
        out["note"] = "not a git repo — git init (see reproducible skill), then commit"
        return out
    files = [os.path.relpath(p, root) for p in paths.values() if os.path.exists(p)]
    subprocess.run(["git", "-C", root, "add", "--"] + files, check=True)
    r = subprocess.run(["git", "-C", root, "commit", "-q", "-m", f"outline: {message}", "--"] + files, capture_output=True, text=True)
    out["committed"] = r.returncode == 0
    if r.returncode == 0:
        out["commit"] = subprocess.run(["git", "-C", root, "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
    else:
        out["note"] = (r.stdout + r.stderr).strip()[:300]
    return out

def outline_fetch_bibtex(doi, key=None):
    """Fetch BibTeX for a DOI from Crossref, optionally set the cite key, stamp verified = {date via doi}."""
    doi = re.sub(r"^https?://(dx\.)?doi\.org/", "", doi.strip())
    url = "https://api.crossref.org/works/" + urllib.parse.quote(doi, safe="/") + "/transform/application/x-bibtex"
    with urllib.request.urlopen(url, timeout=30) as resp:
        bib = resp.read().decode("utf-8").strip()
    if key:
        bib = re.sub(r"^(@\w+\s*\{)\s*[^,]+,", lambda m: m.group(1) + key + ",", bib, count=1)
    stamp = ",\n  verified = {" + datetime.date.today().isoformat() + " via doi}\n}"
    return re.sub(r",?\s*\}\s*$", lambda m: stamp, bib)

def outline_add_bib(root, bibtex):
    """Append a BibTeX entry to paper/refs.bib unless its key already exists."""
    key = re.match(r"\s*@\w+\s*\{\s*([^,\s]+)", bibtex).group(1)
    if key in outline_bib_entries(root):
        return {"key": key, "added": False}
    with open(outline_paths(root)["bib"], "a") as fh:
        fh.write("\n" + bibtex.strip() + "\n")
    return {"key": key, "added": True}
